name: Hello World

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Echo text
        run: echo "Hello, world!"  
